const { query } = require('../db');

// API endpoint for creating a new complaint
const createAssetcomplaints = async (req, res) => {
    const {
        asset_id, charge_nm, room_no, office_name, building, usr_nm, cpu_number, accessory_id,
        complaint_description, complaint_status_id, reported_by
    } = req.body;

    try {

        // Step 1: Check if there is already an existing complaint with the same asset_id and accessory_id
        const existingComplaint = await query(`
            SELECT id, complaint_status_id 
            FROM asset_complaint
            WHERE asset_id = $1 AND accessory_id = $2
            LIMIT 1;
        `, [asset_id, accessory_id]);

        if (existingComplaint.rows.length > 0) {
            const existingStatus = existingComplaint.rows[0].complaint_status_id;

            // If the existing complaint status is 'Open', prevent the new complaint insertion
            if (existingStatus === 1) { // Assuming 1 is the 'Open' status id
                return res.status(400).json({ message: 'Complaint for this asset and accessory already exists with status "Open".' });
            }

            // If status is 'Closed', allow creating a new complaint or updating the existing one
            if (existingStatus === 2) { // Assuming 2 is the 'Closed' status id
                // Insert a new complaint as the previous one is closed
                // Insert the complaint into the database (id is automatically generated by the trigger)
                const result = await query(`
            INSERT INTO asset_complaint (
                asset_id, charge_nm, room_no, office_name, building, usr_nm, cpu_number, accessory_id,
                complaint_description, complaint_status_id, reported_by
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
            RETURNING id;
        `, [
                    asset_id, charge_nm, room_no, office_name, building, usr_nm, cpu_number, accessory_id,
                    complaint_description, complaint_status_id, reported_by
                ]);

                return res.status(201).json({
                    message: 'Complaint created successfully!',
                    complaintId: result.rows[0].id
                });
            }
        }

         // Step 2: If no existing complaint, insert a new complaint (this will happen if no complaint exists)
        
        
        const result = await query(`
            INSERT INTO asset_complaint (
                asset_id, charge_nm, room_no, office_name, building, usr_nm, cpu_number, accessory_id,
                complaint_description, complaint_status_id, reported_by
            ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
            RETURNING id;
        `, [
            asset_id, charge_nm, room_no, office_name, building, usr_nm, cpu_number, accessory_id,
            complaint_description, complaint_status_id, reported_by
        ]);

        return res.status(201).json({
            message: 'Complaint created successfully!',
            complaintId: result.rows[0].id
        });

    } catch (error) {
        console.error(error);
        res.status(500).json({
            message: 'Error creating complaint',
            error: error.message
        });
    }
};





const getAllComplaints = async (req, res) => {
    try {
        const result = await query(`SELECT * FROM asset_complaint`);
        res.status(200).json(result.rows);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Error retrieving complaints', error: err.message });
    }
}

const getComplaintsById = async (req, res) => {
    const { id } = req.params;
    try {
        // Correct SQL query syntax
        const result = await query('SELECT * FROM asset_complaint WHERE id = $1', [id]);

        if (result.rows.length === 0) {
            return res.status(404).json({ message: 'Complaint not found' });
        }

        res.status(200).json(result.rows);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Error retrieving complaints', error: error.message });
    }
}

const updateComplaintsId = async (req, res) => {
    const { id } = req.params;
    const {
        complaint_description, complaint_status_id, resolved_by, resolution_date, resolution_details
    } = req.body;
    try {
        // Correct SQL query syntax
        const result = await query(`
            UPDATE asset_complaint
            SET complaint_description = $1, complaint_status_id = $2, resolved_by = $3, 
                resolution_date = $4, resolution_details = $5
            WHERE id = $6 RETURNING id;
        `, [
            complaint_description, complaint_status_id, resolved_by, resolution_date, resolution_details, id
        ]);

        if (result.rows.length === 0) {
            return res.status(404).json({ message: 'Complaint not found' });
        }

        res.status(200).json({ message: 'Complaint updated successfully', complaintId: result.rows[0].id });

    } catch (error) {
        console.error(err);
        res.status(500).json({ message: 'Error updating complaint', error: err.message });
    }
}






module.exports = { createAssetcomplaints, getAllComplaints, getComplaintsById, updateComplaintsId };
